In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [10]:
a_d1 = np.array([[12,23,4,56,4],[12,12,2,2,2],[1,1,1,1,1]])
print(a_d1)
print(type(a_d1))
print(np.ndim(a_d1))

[[12 23  4 56  4]
 [12 12  2  2  2]
 [ 1  1  1  1  1]]
<class 'numpy.ndarray'>
2


In [16]:
a_d2 = np.array([[12,23,4,56,4],[12,12,2,2,2],[1,1,1,1,1]] , ndmin=5)
print(a_d1)
print(np.ndim(a_d2))
print(a_d2.ndim)

[[12 23  4 56  4]
 [12 12  2  2  2]
 [ 1  1  1  1  1]]
5
5


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [20]:
#empty 
empty_arr = np.empty([4,2])
print(empty_arr)
print('number of dimensions :', empty_arr.ndim)

[[2.49027243e-307             nan]
 [            nan 5.37819833e-310]
 [5.92878775e-323 0.00000000e+000]
 [2.71705710e-316 5.19731021e-293]]
number of dimensions : 2


In [21]:
#ones 
ones_arr = np.ones([4,2])
print(ones_arr)
print('number of dimensions :', ones_arr.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
number of dimensions : 2


In [22]:
#zeros 
zeros_arr = np.zeros([4,2])
print(zeros_arr)
print('number of dimensions :', zeros_arr.ndim)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
number of dimensions : 2


In [27]:
#range

arr_aRange = np.arange(1,5)
print(arr_aRange)

[1 2 3 4]


In [29]:
#Diagonal

arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#negtive indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [38]:
#lispace

ar_linspace = np.linspace(0,25, num=6)
print(ar_linspace)

[ 0.  5. 10. 15. 20. 25.]


In [44]:
#Random functions
#Rand() - 0 to 1
#randn() - close to zero
#ranf() - float in half open interval --> 0.0 to 1.0
#randint() - interger vlaue (min, maz , totalvalue)

random_arr = np.random.rand(4)
print("Rand(): " , random_arr)

random_arr2 = np.random.randn(4)
print("Randn(): " , random_arr2)

random_arr3 = np.random.ranf(4)
print("Ranf(): " , random_arr3
      

random_arr4 = np.random.randint(1,5,5)
print("Randint(): " , random_arr4)

Rand():  [0.36795254 0.13665569 0.6972066  0.41988254]
Randn():  [ 1.24983508  1.3394162  -0.68240169 -0.35169136]
Ranf():  [0.66265988 0.34364355 0.22642019 0.80509046]
Randint():  [3 2 4 3 3]


In [50]:
#Data-type - dtype

var  = np.array(['t','tt',1,2])
print(var.dtype)

var2  = np.array([5,1,2], dtype=np.int8)
print(var2.dtype)


<U11
int8


In [69]:

var2  = np.array([5,1,2], dtype="f")
var3 = np.int_(var2)
var4 = var3.astype(str)

print(var2.dtype)
print(var2)
print(var3.dtype)
print(var3)

print(var4.dtype)
print(var4)

float32
[5. 1. 2.]
int32
[5 1 2]
<U11
['5' '1' '2']


In [71]:
A = np.array([1,2,3,4,5])
B = A + 3
print(B)

[4 5 6 7 8]


In [82]:
# Arithmetic Opeartions
# add(a,b)
# subtract(a,b)
# multiply(a,b)
# divide(a,b)
# mod(a,b)
# power(a,b)
# reciprocal(a)

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

c = np.add(a,b)
print(c)

c = np.subtract(a,b)
print(c)

c = np.multiply(a,b)
print(c)

c = np.divide(a,b)
print(c)

c = np.mod(a,b)
print(c)

c = np.power(a,b)
print(c)

c = np.reciprocal(a)
print(c)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[   1    4   27  256 3125]
[1 0 0 0 0]


In [110]:
# Arithmetic function
# np.min(x) -> return element
# np.max(x) -> return element

# np.argmin(x) -> return index number
# np.argmax(x) -> return index number

# np.sqrt(x)
# np.sin(x)
# np.cos(x)
# np.cumsum(x)

#1D
var = np.array([12,54,6,7,97,467])
print("Min" , np.min(var) , "at :" , np.argmin(var))
print("Max" , np.max(var) , "at :" , np.argmax(var))

# 2D or nD
var = np.array([[12,54,6,7,97,467] , [546,44,5,45,64,5]])
# axis=0 -> clom
# axis=1 -> row

print("2D Min" , np.min(var , axis=1) , "at :" , np.argmin(var))
print("2D Max" , np.max(var , axis=1) , "at :" , np.argmin(var))

var3 = np.array([1,4,16,9,25])
var3_sqrt = np.sqrt(var3)
print("square root :" ,var3_sqrt)

var3_sin = np.sin(var3)
print("Sin :" ,var3_sin)

var3_cos = np.cos(var3)
print("cos :" ,var3_cos)

#cumsum
var4 = np.array([1,2,3,4,5,6,7,8,9])
var4_cumsum = np.cumsum(var4)
print("cumsum :" ,var4_cumsum)


Min 6 at : 2
Max 467 at : 5
2D Min [6 5] at : 8
2D Max [467 546] at : 8
square root : [1. 2. 4. 3. 5.]
Sin : [ 0.84147098 -0.7568025  -0.28790332  0.41211849 -0.13235175]
cos : [ 0.54030231 -0.65364362 -0.95765948 -0.91113026  0.99120281]
cumsum : [ 1  3  6 10 15 21 28 36 45]


In [ ]:
# shape and Reshape

In [111]:
#shape

